sudo: true

notifications:
  email:
    - evantahler@gmail.com
language: node_js
node_js:
  - "4.0"
  - "6.0"
branches:
  only:
    - master

# We'll manually install versions of ES ourselves
# services:
#   - elasticsearch

env:
  - "ES_VERSION=2.3.1"
  - "ES_VERSION=1.7.4"

before_install:
  ## ES has different download locations for each version, so we'll download them both and then just use the one we want
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.4.deb
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb
  ## Now, use the ENV to choose the version
  - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb
  - 'echo -e "index.number_of_shards: 1\nindex.number_of_replicas: 0" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - sudo service elasticsearch restart
  # ES needs some time to start
  - sleep 15
